### ISSUE TITLE
API - Basic Account Endpoints

### ISSUE THREAD

**Issue by IsaacFleetwood** [qi116/iOSApp#6]
Add basic account api endpoints for register and login.
Prerequisites: Create NodeJS server and setup Database

- [x] - Create basic DB wrapper 
- [x] - Create signup endpoint
- - [x] - Accepts email and password
- - [x] - Salt password before storing. 
- [x] - Create login endpoint
- - [x] - Verifies login credentials
- - [x] - Creates session and returns session code.
- [x] - Create logout endpoint
- - [x] - Logs out the user that requested it

**Comment by dzhuang725** [comment]
All API finished and tested.
