### ISSUE TITLE
API - Get Goods

### ISSUE THREAD

**Issue by IsaacFleetwood** [qi116/iOSApp#9]
Add the API endpoints for Get Goods and Get Good Info
- [x] - Created the Get Goods API endpoint for getting the list of goods
- - [x] - Includes pagination
- [x] - Created the Get Good Info API endpoint for getting specific  good info
- - [x] - Accepts the id of the  good which you wish to get the info of.
- - [x] - Includes reviews of the good in the result.

**Comment by dzhuang725** [comment]
Done
